FROM node:26-alpine

RUN apk add --no-cache git

RUN git config --system --add safe.directory '*'

RUN npm install -g pnpm@latest

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install

COPY . .

EXPOSE 5173
EXPOSE 4173

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
